spring.application.name=Learnova

spring.datasource.url=jdbc:postgresql://localhost:5432/Learnova
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jwt.secret=${JWT_SECRET}

spring.servlet.multipart.enabled=true
file.upload-dir=uploads/documents

groq.api.key=${GROQ_API_KEY}
groq.api.url=${GROQ_API_URL}
